spacing: 3
viewDistance: 150
displaySeconds: 60
markers:
  # Default yellow
  CLAIM:
    corner:
      red: 200
      green: 200
      blue: 0
      alpha: 200
    side:
      red: 200
      green: 200
      blue: 0
      alpha: 100
  # Default orange
  ADMIN_CLAIM:
    corner:
      red: 255
      green: 127
      blue: 0
      alpha: 255
    side:
      red: 255
      green: 127
      blue: 0
      alpha: 100
  # Default white
  SUBDIVISION:
    corner:
      red: 255
      green: 255
      blue: 255
      alpha: 200
    side:
      red: 255
      green: 255
      blue: 255
      alpha: 100
  # Default cyan
  INITIALIZE_ZONE:
    corner:
      red: 0
      green: 200
      blue: 200
      alpha: 200
    side:
      red: 0
      green: 200
      blue: 200
      alpha: 100
  # Default red
  CONFLICT_ZONE:
    corner:
      red: 200
      green: 0
      blue: 0
      alpha: 200
    side:
      red: 200
      green: 0
      blue: 0
      alpha: 100
  # Default green
  NATURE_RESTORATION_ZONE:
    corner:
      red: 0
      green: 200
      blue: 0
      alpha: 200
    side:
      red: 0
      green: 200
      blue: 0
      alpha: 100
